### ISSUE TITLE
skip constructor: eqExpr

### ISSUE THREAD

**Issue by sweirich** [antalsz/hs-to-coq#134] opened 2019-06-27 19:36 UTC
Need this one for CSE

```

eqExpr :: InScopeSet -> CoreExpr -> CoreExpr -> Bool
-- Compares for equality, modulo alpha
eqExpr in_scope e1 e2
  = go (mkRnEnv2 in_scope) e1 e2
  where
    go env (Var v1) (Var v2)
      | rnOccL env v1 == rnOccR env v2
      = True

    go _   (Lit lit1)    (Lit lit2)      = lit1 == lit2
    go env (Type t1)    (Type t2)        = eqTypeX env t1 t2
    go env (Coercion co1) (Coercion co2) = eqCoercionX env co1 co2
    go env (Cast e1 co1) (Cast e2 co2) = eqCoercionX env co1 co2 && go env e1 e2
    go env (App f1 a1)   (App f2 a2)   = go env f1 f2 && go env a1 a2
    go env (Tick n1 e1)  (Tick n2 e2)  = eqTickish env n1 n2 && go env e1 e2
...
```

produces 
```
Definition eqExpr : Core.InScopeSet -> Core.CoreExpr -> Core.CoreExpr -> bool :=
  fun in_scope e1 e2 =>
    let fix go arg_0__ arg_1__ arg_2__
              := let go_alt (arg_20__ : Core.RnEnv2) (arg_21__ arg_22__ : Core.CoreAlt)
                  : bool :=
                   match arg_20__, arg_21__, arg_22__ with
                   | env, pair (pair c1 bs1) e1, pair (pair c2 bs2) e2 =>
                       andb (c1 GHC.Base.== c2) (go (Core.rnBndrs2 env bs1 bs2) e1 e2)
                   end in
                 let j_17__ :=
                   match arg_0__, arg_1__, arg_2__ with
                   | _, Core.Lit lit1, Core.Lit lit2 => lit1 GHC.Base.== lit2
                   | env => Core.eqTypeX env t1 t2
                   | env => Coercion.eqCoercionX env co1 co2
                   | env => andb (Coercion.eqCoercionX env co1 co2) (go env e1 e2)
                   | env, Core.App f1 a1, Core.App f2 a2 => andb (go env f1 f2) (go env a1 a2)
                   | env => andb (eqTickish env n1 n2) (go env e1 e2)
   ...
```

**Comment by antalsz** [comment] 2019-06-27 19:37
Also a probable duplicate of #132 – I think all the “too few argument” cases come from the same source

**Closed** 2019-06-27 21:59 UTC
